version: "3.9"
services:
  mysqldb:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: unless-stopped
    ports:
      - $NEXUS_LOCAL_PORT:$NEXUS_DOCKER_PORT
  sonarqube:
    image: sonarqube:8.9.7-community
    container_name: sonarqube
    restart: unless-stopped
    ports:
      - $SONARQUBE_LOCAL_PORT:$SONARQUBE_DOCKER_PORT
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    ports:
      - $PROMETHEUS_LOCAL_PORT:$PROMETHEUS_DOCKER_PORT
    volumes:
      - /etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - $GRAFANA_LOCAL_PORT:$GRAFANA_DOCKER_PORT
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    ports:
      - $PORTAINER_LOCAL_PORT:$PORTAINER_DOCKER_PORT
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    security_opt:
      - no-new-privileges:true
  Devops-education:
    image:achat:1.0
    container_name: Devops-education
    restart: on-failure
    ports:
      - $DEVOPS_EDUCATION_LOCAL_PORT:$DEVOPS_EDUCATION_DOCKER_PORT
    environment:
      spring_application_json: '{ "spring.datasource.url": "jdbc:mysql://mysqldb/achatdb?createDatabaseIfNotExist=true" }'
    build: .
    depends_on:
      - mysqldb